### PR TITLE
form controls: remove unique IDs and rely on shadow dom isolation

### LINKED ISSUE #571: Remove unique ID techniques
As mentioned in #401 we may be able to remove the unique ID techniques we use inside our form atom components.

- [x] check the [Webkit ticket](https://bug.webkit.org/show_bug.cgi?id=199568)
- [x] check that it has indeed been fixed with a safari (use `name` attribute with `cc-toggle` + check `aria-describedby`)
- [x] update `cc-input-number`, `cc-input-text`, `cc-toggle`, `cc-select`!

### PR DESCRIPTION
**Pull request by florian-sanders-cc**
Fixes #571

### CODE REVIEW

**Review by hsablonniere — APPROVED** [review]
Nice :+1:
I was wondering if we should add a name on toggle but this would be a breaking change and maybe we should do this in another commit.

**Comment by florian-sanders-cc** [comment]
> I was wondering if we should add a name on toggle but this would be a breaking change and maybe we should do this in another issue.

Yes, I thought we could deal with names when we switch to element internals and form data ? Or do you want to do it earlier ?
I believe we're missing a "name" attribute and prop on the `cc-select` element.

I'll create the issue anyway and we'll see when we deal with it :wink:

**Review by pdesoyres-cc — APPROVED** [review]
Perfect :+1:

**Comment by hsablonniere** [comment]
> Yes, I thought we could deal with names when we switch to element internals and form data ? Or do you want to do it earlier ?

Yes, we'll do this when doing element internals

**Pull request merged**
