### PR TITLE
legacy pricing components (v7.12.0):  fix shoelace and allow custom product features

### LINKED ISSUE #781: legacy `cc-pricing-table/product`: allow custom features without translations
## Context

On the Clever Cloud Website, we want to be able to use the `cc-pricing-product` component to showcase a product not included within the API yet, with features that were not part of the original list of features.

The pricing components filter out features that have no translation registered.

This means we cannot add features without adding new translations and releasing a new version of the component.

## Things to do:

- from the 7.12 version of the components, create a new branch and update the components to stop filtering out features that have no translation,
- create a 7.13 branch to receive the modifications,
- manually release the 7.13.0 version on CDN and npm.

### LINKED ISSUE #787: legacy `cc-pricing-header` (version < 11.0.0): does not work with chrome > 114
## Context

The currency and zone selects do not work on Chrome > 114.

There is a conflict between `popover` used by `Shoelace` and the new `Popover API` released on Chrome.

## Solution

Since the Website is the only consumer of the `cc-pricing-header` and it uses the version 7.9.0 of this component, we will update the Shoelace dependency to fix this issue and release it in a `7.13.0`.

The `7.13.0` version of `cc-pricing-header` will be the only working version on Chrome below the `11.0.0` version of the components.

### PR DESCRIPTION
**Pull request by florian-sanders-cc**
Fixes #781 
Fixes #787

## What does this PR do?

- Updates the shoelace dependency to fix the issue with `cc-pricing-header` and Chrome. 
- Modifies `cc-pricing-table` to stop filtering features that have no translations and display the raw code as the feature name within the table headers.

## How to review?

Bear in mind that these modifications are quick fixes:
- Review both commits.
- Check out these three stories:
  - [cc-pricing-header](https://clever-components-preview.cellar-c2.services.clever-cloud.com/7.13.0/index.html?path=/story/%F0%9F%9B%A0-pricing-cc-pricing-header--default-story) => play with the select. The design should be the same as the pricing page of the website + everything should be working correctly (check the website on FF and check the story with Chrome).
  - [Product with custom features](https://clever-components-preview.cellar-c2.services.clever-cloud.com/7.13.0/index.html?path=/story/%F0%9F%9B%A0-pricing-cc-pricing-product--data-loaded-with-custom-product-features) => you should see 5 new product features displayed (logs, backup retention, backup frequency, migration, dedicated).
  - [Table with Fake Product](https://clever-components-preview.cellar-c2.services.clever-cloud.com/7.13.0/index.html?path=/story/%F0%9F%9B%A0-pricing-cc-pricing-table--data-loaded-with-fake-product) => you should see `ignored-because-not-translated` but not `ignored-because-not-listed` (this story already existed and before the modifications, both of these categories were hidden).

I have already checked that `cc-pricing-header` events are still working (updating the currency / zone of all other components) using a demo of the smart.
I don't think you need to check it again but you can if you want :wink: (you need to set up a new demo file yourself since this version relies on the old project structure).

### CODE REVIEW

**Review by pdesoyres-cc — CHANGES_REQUESTED** [review]
Well done.
LGTM, except that the `_features` property is now useless.

**Comment by florian-sanders-cc** [comment]
> Well done. LGTM, except that the `_features` property is now useless.

Indeed, thanks!
The `_features` property has been removed :+1:

**Review by pdesoyres-cc — APPROVED** [review]

**Review by roberttran-cc — APPROVED** [review]
LGTM!

Nitpick (non-blocking): I think there's a comment which is not relevant anymore, in `stories/pricing/cc-pricing-table.stories.js` line 8: `// Some features will be ignored because they cannot be translated`.

**Review by Galimede — APPROVED** [review]
LGTM, GG! :clap:

**Review by hsablonniere — APPROVED** [review]

**Pull request merged**
