### PR TITLE
cc-input-number: controls mode disabled opacity

### LINKED ISSUE #229: cc-input-number: disable buttons when necessary
We need to set `disabled` on the minus/plus buttons:

* `disabled` => both buttons are visible and disabled
* `readonly`  => both buttons are visible and disabled
* `value` === `min` => minus button is disabled
* `value` === `max` => plus button is disabled

We should style these disabled state with some kind of `opacity: 0.25`.

### PR DESCRIPTION
**Pull request by Galimede**
Fixes #229

### CODE REVIEW

**Comment by hsablonniere** [comment]
@Galimede I guess my sentence was not clear, sorry:

> We need the minus and plus buttons to be disabled when not possible

I meant, when `min=0`, disable the minus button if value is `0`.
Same behaviour for the plus button when value is equal to max.

About the CHANGELOG, I think we should refer to components with MD backticks and HTML tag markers like this: `<cc-input-number>` and not like this: cc-input-number.

I failed to do that in the 3 latest changelog entries, sorry.
Can you update those in a separate commit?

**Comment by Galimede** [comment]
Here you go @hsablonniere😉

**Comment by hsablonniere** [comment]
@Galimede Awesome, can you add a commit where you rewrite the last CHANGELOG entries where I forgot to correctly refer to components with `<cc-the-component>`?

**Comment by Galimede** [comment]
Sure 😉

**Comment by hsablonniere** [comment]
Let's go then ;-)

**Pull request merged**
