### PR TITLE
build(cdn): order the cdn entries

### LINKED ISSUE #803: CDN UI (release): list versions in semver order
## Context

Currently the CDN (release) lists the version `7.13.1` first because it was the last version created.

Versions should be listed in semver order to avoid this.

Question: should it be done by the client (CDN UI) or the worker directly within the manifest? Or both?

### PR DESCRIPTION
**Pull request by pdesoyres-cc**
Fixes #803

### CODE REVIEW

**Review by hsablonniere — APPROVED** [review]
Very nice @pdesoyres-cc, thanks :+1:

**Review by roberttran-cc — APPROVED** [review]
Nice job! :rocket: 

And TIL about `localCompare`'s `sensivity` parameter. :exploding_head:

**Comment by pdesoyres-cc** [comment]
:warning: Migration script

* [ ] reset upgrade script: `git reset HEAD~1`
* [ ] upgrade staging env: run `node tasks/cdn-upgrade.js staging`
* [ ] upgrade preview env: run `node tasks/cdn-upgrade.js preview`
* [ ] upgrade release env: run `node tasks/cdn-upgrade.js release`

**Comment by pdesoyres-cc** [comment]
Upgrade procedure success :tada:

**Pull request merged**
