### PR TITLE
docs(contributing): add standard contribution doc with symlink

### PR DESCRIPTION
**Pull request by Slashgear**
## Why
CONTRIBUTING.md file is a standard in oss repository in order to inform users how they can/should contribute. [You can read more on this file on this documentaion](https://contributing.md/how-to-build-contributing-md/)

## How
- use symlink from existing contributing documentation in order to add the CONTRIBUTING.md file in the root directory

_Hope this contribution will help 🤗_

### CODE REVIEW

**Review by pdesoyres-cc — APPROVED** [review]
Thank you for this contribution! :muscle:

**Review by florian-sanders-cc — APPROVED** [review]

**Review by pdesoyres-cc — CHANGES_REQUESTED** [review]
After discussion with the team, we would prefer to avoid symlinks. Alternatively, you could move the `/docs/guides/how-to-contribute.md` file to `/CONTRIBUTE.md`. Storybook will continue to place the file at the same place, thanks to the Front Matter.

**Comment by Slashgear** [comment]
Ok, I could do that :)

**Comment by Slashgear** [comment]
First contribution on this project, **+0-0** 
🤣

**Review by pdesoyres-cc — APPROVED** [review]

**Review by Galimede — APPROVED** [review]

**Comment by hsablonniere** [comment]
@Slashgear I squashed your commits into one, renamed it and merged it. Thanks again for your contribution :blush: :clap:

**Comment by hsablonniere** [comment]
:tada: https://github.com/CleverCloud/clever-components/commit/b2a4ef697bdd462cf3d60eb5c154873d8c21b0f5

I forgot to remove the mention of the symlink in the body of the commit :disappointed:

**Pull request closed without merging**
