### PR TITLE
ci(test-and-build): add some missing tasks and reorganize tasks

### LINKED ISSUE #625: Update GitHub Actions with type check and import tasks
CI/CD should include:
- `npm run components:check-type-imports`
- `npm run typecheck`
- `test:cem`

### LINKED ISSUE #712: Reorganize test-and-build GitHub action workflow steps
In addition to running unit tests and performing builds, this workflow runs some code quality checks.

Unit tests are run very early and take a long time to process.

It would be better to start the quick steps before the slow ones.

Let's also take the opportunity to rename the tasks.

### PR DESCRIPTION
**Pull request by pdesoyres-cc**
Fixes #625 
Fixes #712

### CODE REVIEW

**Review by Galimede — APPROVED** [review]
Does putting quotes in the name of the task changes anything ?  :thinking: 

Otherwise, LGTM GG! :+1:

**Comment by pdesoyres-cc** [comment]
> Does putting quotes in the name of the task changes anything ? thinking

If you don't put quotes, the square brackets break the yaml format

**Review by roberttran-cc — APPROVED** [review]
Neat! GG! :ok_hand:

**Review by florian-sanders-cc — APPROVED** [review]
Nice ! I really like the reorganization with the fail fast strategy :clap:

**Review by hsablonniere — APPROVED** [review]
Awesome! I really like how it's named and organized :clap:

**Pull request merged**
